name: flow_queue
description: "A Flutter package providing a persistent task queue with priorities."
version: 1.2.0

homepage: https://pub.dev/packages/flow_queue
repository: https://github.com/harsh4114/flow_queue
issue_tracker: https://github.com/harsh4114/flow_queue/issues

topics:
  - background
  - async
  - sqlite
  - api
  - flow-queue

environment:
  sdk: ^3.12.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.9.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
